{{- if .Values.restapi.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cawemo.fullname" . }}-{{ .Values.restapi.containerName }}
  labels:
    {{- include "cawemo.labels" . | nindent 4 }}
    {{- include "restapi.labels" . | nindent 4 }}

spec:
  type: {{ .Values.restapi.service.type }}
  ports:
    - port: {{ .Values.restapi.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 8091
      targetPort: 8091
      protocol: TCP
      name: http-admin
  selector:
    {{- include "restapi.selectorLabels" . | nindent 4 }}
{{- end }}