{{- if .Values.adminer.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cawemo.fullname" . }}-{{ .Values.adminer.containerName }}
  labels:
    {{- include "cawemo.labels" . | nindent 4 }}
    {{- include "adminer.labels" . | nindent 4 }}

spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.general.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "adminer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "adminer.selectorLabels" . | nindent 8 }}

    spec:
      {{- with .Values.adminer.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      serviceAccountName: {{ include "cawemo.serviceAccountName" . }}

      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}

      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.adminer.image.repository }}:{{ .Values.adminer.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.adminer.image.pullPolicy }}

{{/*          env:*/}}

          ports:
            - name: {{ .Values.adminer.service.portName }}
              containerPort: {{ .Values.adminer.service.port }}
              protocol: TCP

{{/* Rediness probe must be defined correctly otherwise the Service Endpoints will not be assigned. Thus the app will not be accessible externally */}}
{{/*          readinessProbe:*/}}
{{/*            httpGet:*/}}
{{/*              path: optimze*/}}
{{/*              port: http*/}}
{{/*            initialDelaySeconds: 60*/}}
{{/*            periodSeconds: 60*/}}

{{/*          resources:*/}}
{{/*            {{- toYaml .Values.resources | nindent 12 }}*/}}

{{/*          volumeMounts:*/}}
{{/*          - mountPath: /cawemo/config/environment-config.yaml*/}}
{{/*            subPath: environment-config.yaml*/}}
{{/*            name: environment-config*/}}

{{/*          - mountPath: /cawemo/config/OptimizeLicense.txt*/}}
{{/*            subPath: OptimizeLicense.txt*/}}
{{/*            name: license*/}}

{{/*      volumes:*/}}
{{/*      - name: environment-config*/}}
{{/*        configMap:*/}}
{{/*          name: environment-config*/}}

{{/*      - name: license*/}}
{{/*        secret:*/}}
{{/*          secretName: license*/}}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end}}
