{{- if .Values.websockets.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cawemo.fullname" . }}-{{ .Values.websockets.containerName }}
  labels:
    {{- include "cawemo.labels" . | nindent 4 }}
    {{- include "websockets.labels" . | nindent 4 }}

spec:
  type: {{ .Values.websockets.service.type }}
  ports:
    - port: {{ .Values.websockets.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "websockets.selectorLabels" . | nindent 4 }}
{{- end }}