{{- if .Values.restapi.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cawemo.fullname" . }}-{{ .Values.restapi.containerName }}
  labels:
    {{- include "cawemo.labels" . | nindent 4 }}
    {{- include "restapi.labels" . | nindent 4 }}

spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.general.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "restapi.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "restapi.selectorLabels" . | nindent 8 }}

    spec:

      {{- with .Values.restapi.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      serviceAccountName: {{ include "cawemo.serviceAccountName" . }}

      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}

      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.restapi.image.repository }}:{{ .Values.restapi.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.restapi.image.pullPolicy }}

          env:
            - name: DEBUG
              value: "{{ .Values.restapi.debug }}"
            - name: JAVA_OPTIONS
              value: {{ .Values.restapi.env.javaOpts}}
            - name: CAWEMO_DB_HOST
              value: {{ .Values.restapi.env.dbHost}}
            - name: CAWEMO_DB_PORT
              value: "{{ .Values.restapi.env.dbPort}}"
            - name: CAWEMO_DB_NAME
              value: {{ .Values.restapi.env.dbName}}
            - name: CAWEMO_DB_USER
              value: {{ .Values.restapi.env.dbUser}}
            - name: CAWEMO_DB_PASSWORD
              value: {{ .Values.restapi.env.dbPassword}}

{{/*            - name: CAWEMO_DB_USER*/}}
{{/*              valueFrom:*/}}
{{/*                secretKeyRef:*/}}
{{/*                  name: {{ .Values.restapi.env.credentialsSecertName }}*/}}
{{/*                  key: DB_USERNAME*/}}
{{/*            - name: CAWEMO_DB_PASSWORD*/}}
{{/*              valueFrom:*/}}
{{/*                secretKeyRef:*/}}
{{/*                  name: {{ .Values.restapi.env.credentialsSecertName }}*/}}
{{/*                  key: DB_PASSWORD*/}}

            - name: CAWEMO_MAIL_HOST
              value: {{ .Values.restapi.env.mailHost}}
            - name: CAWEMO_MAIL_PORT
              value: "{{ .Values.restapi.env.mailPort}}"
            - name: CAWEMO_MAIL_USER
              value: {{ .Values.restapi.env.mailUser}}
            - name: CAWEMO_MAIL_PASSWORD
              value: {{ .Values.restapi.env.mailPassword}}
            - name: CAWEMO_MAIL_ENABLE_TLS
              value: "{{ .Values.restapi.env.mailEnableTLS}}"
            - name: CAWEMO_MAIL_FROM_ADDRESS
              value: "{{ .Values.restapi.env.mailFromAddress}}"
            - name: CAWEMO_MAIL_FROM_NAME
              value: {{ .Values.restapi.env.mailFromName}}
            - name: CAWEMO_MIGRATION_MIGRATE
              value: "{{ .Values.restapi.env.cawemoMigrate}}"
            - name: CAWEMO_PUSHER_APP_ID
              value: "{{ .Values.restapi.env.websocketAppId}}"
            - name: CAWEMO_PUSHER_KEY
              value: "{{ .Values.restapi.env.websocketKey}}"
            - name: CAWEMO_PUSHER_SECRET
              value: "{{ .Values.restapi.env.websocketSecret}}"
            - name: CAWEMO_PUSHER_HOST
              value: {{ .Values.restapi.env.websocketHost}}
            - name: CAWEMO_PUSHER_PORT
              value: "{{ .Values.restapi.env.websocketPort }}"
            - name: CAWEMO_SERVER_CACHE_TEMPLATES
              value: "{{ .Values.restapi.env.serverCacheTemplates}}"
            - name: CAWEMO_SERVER_SHUTDOWN_TIMEOUT
              value: "{{ .Values.restapi.env.serverShutDownTimeout}}"
            - name: CAWEMO_SERVER_URL
              value: {{ .Values.restapi.env.cawemoServerUrl}}
            - name: CLIENT_THEME_COLORS_PRIMARY
              value: "{{ .Values.restapi.env.cleintThemeColorsPrimary}}"
            - name: CLIENT_THEME_COLORS_SECONDARY
              value: "{{ .Values.restapi.env.clientThemeColorsSecondary}}"
            - name: CLIENT_THEME_COLORS_ACCENT
              value: "{{ .Values.restapi.env.clientThemeColorsAccent}}"
            - name: LICENSE_FILE_PATH
              value: {{ .Values.restapi.env.licenseFilePath}}

          ports:
            - name: {{ .Values.restapi.service.portName }}
              containerPort: {{ .Values.restapi.service.port }}
              protocol: TCP

{{/* Rediness probe must be defined correctly otherwise the Service Endpoints will not be assigned. Thus the app will not be accessible externally*/}}
{{/*          readinessProbe:*/}}
{{/*            httpGet:*/}}
{{/*              path: optimze*/}}
{{/*              port: http*/}}
{{/*            initialDelaySeconds: 60*/}}
{{/*            periodSeconds: 60*/}}

          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          volumeMounts:
{{/*          - mountPath: /cawemo/config/environment-config.yaml*/}}
{{/*            subPath: environment-config.yaml*/}}
{{/*            name: environment-config*/}}

          - mountPath: /config.key
            subPath: config.key
            name: license

      volumes:
{{/*      - name: environment-config*/}}
{{/*        configMap:*/}}
{{/*          name: environment-config*/}}

      - name: license
        secret:
          secretName: license

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}