apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "cawemo.labels" . | nindent 4 }}
  name: license
stringData:
  config.key:
    --------------- BEGIN CAMUNDA LICENSE KEY ---------------
    --------------- END CAMUNDA LICENSE KEY ---------------
