{{- if .Values.iam.router.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cawemo.fullname" . }}-{{ .Values.iam.router.containerName }}
  labels:
    {{- include "cawemo.labels" . | nindent 4 }}
    {{- include "iam-router.labels" . | nindent 4 }}

spec:
  type: {{ .Values.iam.router.service.type }}
  ports:
    - port: {{ .Values.iam.router.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "iam-router.selectorLabels" . | nindent 4 }}
{{- end }}