{{- if .Values.iam.backend.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cawemo.fullname" . }}-{{ .Values.iam.backend.containerName }}
  labels:
    {{- include "cawemo.labels" . | nindent 4 }}
    {{- include "iam-backend.labels" . | nindent 4 }}

spec:
  type: {{ .Values.iam.backend.service.type }}
  ports:
    - port: {{ .Values.iam.backend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "iam-backend.selectorLabels" . | nindent 4 }}
{{- end }}